/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
	scheme "github.com/google/knative-gcp/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StackdriversGetter has a method to return a StackdriverInterface.
// A group's client should implement this interface.
type StackdriversGetter interface {
	Stackdrivers(namespace string) StackdriverInterface
}

// StackdriverInterface has methods to work with Stackdriver resources.
type StackdriverInterface interface {
	Create(*v1alpha1.Stackdriver) (*v1alpha1.Stackdriver, error)
	Update(*v1alpha1.Stackdriver) (*v1alpha1.Stackdriver, error)
	UpdateStatus(*v1alpha1.Stackdriver) (*v1alpha1.Stackdriver, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Stackdriver, error)
	List(opts v1.ListOptions) (*v1alpha1.StackdriverList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Stackdriver, err error)
	StackdriverExpansion
}

// stackdrivers implements StackdriverInterface
type stackdrivers struct {
	client rest.Interface
	ns     string
}

// newStackdrivers returns a Stackdrivers
func newStackdrivers(c *EventsV1alpha1Client, namespace string) *stackdrivers {
	return &stackdrivers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the stackdriver, and returns the corresponding stackdriver object, and an error if there is any.
func (c *stackdrivers) Get(name string, options v1.GetOptions) (result *v1alpha1.Stackdriver, err error) {
	result = &v1alpha1.Stackdriver{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stackdrivers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Stackdrivers that match those selectors.
func (c *stackdrivers) List(opts v1.ListOptions) (result *v1alpha1.StackdriverList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StackdriverList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stackdrivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested stackdrivers.
func (c *stackdrivers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("stackdrivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a stackdriver and creates it.  Returns the server's representation of the stackdriver, and an error, if there is any.
func (c *stackdrivers) Create(stackdriver *v1alpha1.Stackdriver) (result *v1alpha1.Stackdriver, err error) {
	result = &v1alpha1.Stackdriver{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("stackdrivers").
		Body(stackdriver).
		Do().
		Into(result)
	return
}

// Update takes the representation of a stackdriver and updates it. Returns the server's representation of the stackdriver, and an error, if there is any.
func (c *stackdrivers) Update(stackdriver *v1alpha1.Stackdriver) (result *v1alpha1.Stackdriver, err error) {
	result = &v1alpha1.Stackdriver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stackdrivers").
		Name(stackdriver.Name).
		Body(stackdriver).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *stackdrivers) UpdateStatus(stackdriver *v1alpha1.Stackdriver) (result *v1alpha1.Stackdriver, err error) {
	result = &v1alpha1.Stackdriver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stackdrivers").
		Name(stackdriver.Name).
		SubResource("status").
		Body(stackdriver).
		Do().
		Into(result)
	return
}

// Delete takes name of the stackdriver and deletes it. Returns an error if one occurs.
func (c *stackdrivers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stackdrivers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *stackdrivers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stackdrivers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched stackdriver.
func (c *stackdrivers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Stackdriver, err error) {
	result = &v1alpha1.Stackdriver{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("stackdrivers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
