/*
Copyright 2019 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/knative-gcp/pkg/apis/events/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStackdrivers implements StackdriverInterface
type FakeStackdrivers struct {
	Fake *FakeEventsV1alpha1
	ns   string
}

var stackdriversResource = schema.GroupVersionResource{Group: "events.cloud.google.com", Version: "v1alpha1", Resource: "stackdrivers"}

var stackdriversKind = schema.GroupVersionKind{Group: "events.cloud.google.com", Version: "v1alpha1", Kind: "Stackdriver"}

// Get takes name of the stackdriver, and returns the corresponding stackdriver object, and an error if there is any.
func (c *FakeStackdrivers) Get(name string, options v1.GetOptions) (result *v1alpha1.Stackdriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(stackdriversResource, c.ns, name), &v1alpha1.Stackdriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Stackdriver), err
}

// List takes label and field selectors, and returns the list of Stackdrivers that match those selectors.
func (c *FakeStackdrivers) List(opts v1.ListOptions) (result *v1alpha1.StackdriverList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(stackdriversResource, stackdriversKind, c.ns, opts), &v1alpha1.StackdriverList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StackdriverList{ListMeta: obj.(*v1alpha1.StackdriverList).ListMeta}
	for _, item := range obj.(*v1alpha1.StackdriverList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stackdrivers.
func (c *FakeStackdrivers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(stackdriversResource, c.ns, opts))

}

// Create takes the representation of a stackdriver and creates it.  Returns the server's representation of the stackdriver, and an error, if there is any.
func (c *FakeStackdrivers) Create(stackdriver *v1alpha1.Stackdriver) (result *v1alpha1.Stackdriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(stackdriversResource, c.ns, stackdriver), &v1alpha1.Stackdriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Stackdriver), err
}

// Update takes the representation of a stackdriver and updates it. Returns the server's representation of the stackdriver, and an error, if there is any.
func (c *FakeStackdrivers) Update(stackdriver *v1alpha1.Stackdriver) (result *v1alpha1.Stackdriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(stackdriversResource, c.ns, stackdriver), &v1alpha1.Stackdriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Stackdriver), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStackdrivers) UpdateStatus(stackdriver *v1alpha1.Stackdriver) (*v1alpha1.Stackdriver, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(stackdriversResource, "status", c.ns, stackdriver), &v1alpha1.Stackdriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Stackdriver), err
}

// Delete takes name of the stackdriver and deletes it. Returns an error if one occurs.
func (c *FakeStackdrivers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(stackdriversResource, c.ns, name), &v1alpha1.Stackdriver{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStackdrivers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(stackdriversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.StackdriverList{})
	return err
}

// Patch applies the patch and returns the patched stackdriver.
func (c *FakeStackdrivers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Stackdriver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stackdriversResource, c.ns, name, pt, data, subresources...), &v1alpha1.Stackdriver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Stackdriver), err
}
